### ISSUE TITLE
Handling Job Retries Elegantly

### ISSUE THREAD

**Issue by bartclarkson** [brianlmoon/net_gearman#28]
Hi Brian.  I was looking at this: https://github.com/brianlmoon/GearmanManager/issues/87 .  I also looked at your WORK_EXCEPTION issue you create here awhile back.

Basically, I want a worker to retry itself x times and then call support.

Here the worker does a call to exec(), and the output of that command indicates whether the process should be retried. 

Am I failing to grasp the preferred approach?  Thanks!

```php
class Net_Gearman_Job_UntrustworthyJob extends \Net_Gearman_Job_Common {
    public function run($args) {
        $retries = $args['retries'];
        $max_retries = $args['max_retries'];
        $job_server = $args['job_server'];
        $whatever = $args['parameter'];
        $command = PHP_BINDIR . '/php command_might_be_doomed ' . $whatever;
        exec($command, $lines);
        if (end($lines) != 'COMPLETE')) {
            if ($retries == $max_retries) {
                // Create Case in Zendesk for Developer with the $args and other relevant details.
            }
            else {
                // add Job again, incrementing the $args['retries'].
                $args['retries']++;
                $gmclient= new \Net_Gearman_Client($job_server);
                $result = $gmclient->UntrustworthyJob($args);
            }
        }
    }
}

**Comment by brianlmoon** [comment]
That is a suitable approach. It's not what the other issue was talking about. In his case, the job was failing in an unknown state. i.e. it was likely throwing a fatal PHP error and exiting. 

In your case, you are handling retries at the application level. Which is fine. It's not part of the Gearman spec. But a lot of the things I do in workers are not part of the spec. They are what I need to do to make my application work.

Are you having an issue with this approach?

**Comment by brianlmoon** [comment]
My only concern with this approach is that each retry will get a unique job id. This means that another job with the same $args[paraeters] could get into the queue with a different retry count. You can't really avoid this however. If you submit this job with the same unique id, it will not get worked because this worker is already working this job.

**Comment by bartclarkson** [comment]
Ok, cool.  Yeah, it seems to work well.  But I sure feel better having had someone in the Gearman game give it the old eyeball.

I wondered if you were going to say, "What you need to do is do a die() right after you call ->xyz($args) to change and persist your changes to the arguments before causing the job to be retried."  Or some kind of funky deal hinging on custom callback functions with the client.  I was apprehensive about the complexities, and seriously Loathe to mess with anything that my rather vanilla implementation of Gearman Manager is presently making simple (hat tip).

I think I'm safe from multiple (re)tries tied to the same essential result being pushed up to the client from multiple sources.  The application produces the unique parameters a single time and simply waits for a database update (which is driven by a successful worker).

I understood the other issue of retries to be more of a global protection mechanism, and setting that on the gearmand daemon makes perfect sense.  A vanilla Health Check is on the lookout for EC2's under the worker load balancer that are exhibiting the sorts of problems that would cause a true WORK_FAIL event.

Hope you have an awesome day. Thanks!
