### ISSUE TITLE
hi Net_Gearman is already installed

### ISSUE THREAD

**Issue by huangyunjian** [brianlmoon/net_gearman#32]
hi ,pear install Net_Gearman
pear/Net_Gearman is already installed and is the same as the released version 0.2.3

tips:
Net_Gearman package not found!

You can get it at http://pear.php.net/package/Net_Gearman/ or install by pear:

pear install Net_Gearman

**Comment by brianlmoon** [comment]
The version on PEAR is quite old and unmaintained. It's best to install it via Composer.

**Comment by webhacking** [comment]
is already installed and is the same as the released version;
