### ISSUE TITLE
Could not find package brianlmoon/net_gearman at any version for your minimum-stability

### ISSUE THREAD

**Issue by antoiba86** [brianlmoon/net_gearman#33]
Hello,
I am trying to install your GearmanManager and I need this package.
In order to install I prefer always composer so I used the instructions that you have on the readme.
But it's not working because the minimum stability I need is stable.
So to download the package I wrote on my composer.
```

"require": {
                "brianlmoon/net_gearman": "@dev"
	}
```

Because with Composer I couldn't do it otherwise.

**Comment by brianlmoon** [comment]
This works for me. What errors do you see?
```
$ composer require brianlmoon/net_gearman
Using version ^1.0 for brianlmoon/net_gearman
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing brianlmoon/net_gearman (1.0.2): Loading from cache
Writing lock file
Generating optimized autoload files
```
