### ISSUE TITLE
If connection drops in the middle of worker init, then socket is not connected, but Worker destruct still tries to blindly write to it

### ISSUE THREAD

**Issue by indreka** [brianlmoon/net_gearman#39]
[vendor/brianlmoon/net_gearman/Net/Gearman/Connection.php:283] "socket_write() expects parameter 1 to be resource, null given"
    Utils/Gearman/GearmanPearManager.php:100 call_user_func_array(<Array>, <Array>)
    Utils\Gearman\GearmanPearManager->Utils\Gearman\{closure}(2, "socket_write() expects parameter 1 to be resource, null given", "vendor/brianlmoon/net_gearman/Net/Gearman/Connection.php", 283, <Array>)
    vendor/brianlmoon/net_gearman/Net/Gearman/Connection.php:283 socket_write("", "REQ", 12)
    vendor/brianlmoon/net_gearman/Net/Gearman/Worker.php:739 send("reset_abilities")
    vendor/brianlmoon/net_gearman/Net/Gearman/Worker.php:730 close("gearman1")
    vendor/brianlmoon/net_gearman/Net/Gearman/Worker.php:756 endWork()
    Net_Gearman_Worker->__destruct()

**Comment by indreka** [comment]
From what I see, the Connection class does not have isClosed or similar helper function and send($command) also does not check if socket is even connected.
Our logging ignores the @ suppression to catch all hidden errors and warnings and this socket_write issue was revealed due to that

**Comment by brianlmoon** [comment]
I think this will solve the problem. https://github.com/brianlmoon/net_gearman/commit/288afc6e018da3600237e6ea1629d3a8517cfe95

**Comment by indreka** [comment]
Sorry for late reply, that patch will trigger a lot more warnings actually...
    public function connect($host, $timeout = 250)
You are now calling function connect without providing the host parameter which will not work at all, so now there are a few more errors...

Checking the codeflow, the connect originally was/is only called in constructor. This means constructor must record the host and timeout parameters in private properties that the connect function can then use and re-use. But that approach still has lots of issues.

Firstly the main issue still remains: if the connection has dropped, then there is no point in the Worker to write "reset_abilities" to a connection that is not open anymore. When you open a new connection, just to tell "reset_abilities" and then close it, it is unneeded open/close operation, because server side already should understand that connection dropped.

If the connection drops then the correct place to handle it is in the Worker because for new connection the abilities must also be resent... So reconnecting in the middle of Connection class without sending abilities list is incorrect...
