### ISSUE TITLE
Could you please confirm this work with php7?

### ISSUE THREAD

**Issue by stccorp** [brianlmoon/net_gearman#45]
Could you please confirm this work with php7?

Any particular 7 version?  

Thank you

**Comment by brianlmoon** [comment]
Yes, I use it daily with PHP 7.1.

**Comment by j03k64** [comment]
I can confirm it works on PHP 7.2, PHP 7.3 and PHP 7.4 for millions of jobs/day. I need to actually open a pull requests for PHP 8.0 fixes for it though.

**Comment by brianlmoon** [comment]
We use it daily with PHP 7.3 and 7.4.

**Comment by brianlmoon** [comment]
@j03k64 
> I can confirm it works on PHP 7.2, PHP 7.3 and PHP 7.4 for millions of jobs/day. I need to actually open a pull requests for PHP 8.0 fixes for it though.

I would love that. I have just started building PHP 8 docker containers and have not tried running Gearman workers with it yet.
